[package]
name = "schedul_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo-watch = "8.4.1"
kafka = "0.10.0"
nickel = "*"
serde_json = "1.0.108"
tokio = { version = "1.11.0", features = ["full"] }
tokio-cron-scheduler = "*"
